version: 0.2

phases:
  build:
    commands:
    - echo "This is build phase... Zipping my lambda function"
    - zip -r deployment_package.zip app.js
  post_build:
    commands:
    - echo "Deploying to the Lambda"
    - aws lambda update-function-code --function-name  my-lambda-cicd --zip-file fileb://deployment_package.zip
artifacts:
  type: zip
  paths:
    - '*'